apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Harness GitOps Lab</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin-top: 100px;
            background: #f2f5f9;
          }
          .card {
            background: white;
            width: 500px;
            margin: auto;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 4px 14px rgba(0,0,0,0.15);
          }
        </style>
      </head>
      <body>
        <div class="card">
          <h1>Harness GitOps Website</h1>
          <h2>Version 2</h2>
          <p>This application was deployed from GitHub using Harness GitOps.</p>
        </div>
      </body>
    </html>
